# Accents
PRODUCT_PACKAGES += \
	AccentColorBlueGrayOverlay \
	AccentColorCoralOverlay \
	AccentColorCyanOverlay \
	AccentColorFlatPinkOverlay \
	AccentColorIndigoOverlay \
	AccentColorLightPurpleOverlay \
	AccentColorPinkOverlay \
	AccentColorRedOverlay \
	AccentColorTealOverlay \
	AccentColorCocaColaOverlay \
        AccentColorMetallicGoldOverlay \
        AccentColorInfernoRedOverlay \
        AccentColorDorsetGoldOverlay \
        AccentColorUbuntuOverlay \
        AccentColorSalmonOverlay \
        AccentColorPornhubOverlay \
        AccentColorMatrixOverlay \
        AccentColorEvolutionBlueOverlay \
	AccentColorEvolutionGreenOverlay \
	AccentColorEvolutionRedOverlay \
	AccentColorEvolutionYellowOverlay \
        AccentColorCocaColaOverlay \
	AccentColorDiscordOverlay \
	AccentColorFerrariRedOverlay \
	AccentColorGoldenShowerOverlay \
	AccentColorJollibeeOverlay \
        AccentColorNextbitOverlay \
	AccentColorOnePlusOverlay \
	AccentColorParanoidOverlay \
	AccentColorPepsiOverlay \
        AccentColorRazerOverlay \
        AccentColorStarbucksOverlay \
	AccentColorXboxOverlay \
	AccentColorXiaomiOverlay \
        AccentColorOneplusOverlay
